using DevExpress.XtraReports.UI;
using Infragistics.Win;
using Infragistics.Win.Misc;
using Infragistics.Win.UltraWinGrid;
using Micromind.ClientLibraries;
using Micromind.ClientUI.Libraries;
using Micromind.Common.Data;
using Micromind.Common.Interfaces;
using Micromind.DataControls;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;

namespace Micromind.ClientUI.Reports.Customers
{
	public class FixedAssetListReport : Form, IForm
	{
		private ScreenAccessRight screenRight;

		private IContainer components;

		private Button buttonOK;

		private CheckBox checkBoxShowInactive;

		private Button buttonClose;

		private FixedAssetSelector FixedAssetSelector;

		private RadioButton radioButtonDivision;

		private Label label6;

		private Label label1;

		private Label label7;

		private Label label2;

		private RadioButton radioButtonDepartment;

		private UltraGroupBox ultraGroupBox1;

		private DivisionComboBox comboBoxFromDivision;

		private DivisionComboBox comboBoxToDivision;

		private DepartmentComboBox comboBoxFromDepartment;

		private DepartmentComboBox comboBoxToDepartment;

		private RadioButton radioButtoncountry;

		private RadioButton radioButtoncompany;

		private Label label3;

		private Label label4;

		private Label label5;

		private Label label8;

		private GenericListComboBox ComboBoxCompanyFrom;

		private GenericListComboBox ComboBoxCompanyTo;

		private CountryComboBox comboBoxCountryFrom;

		private CountryComboBox comboBoxCountryTo;

		public ScreenAreas ScreenArea => ScreenAreas.ReportsCustomer;

		public int ScreenID => 7014;

		public ScreenTypes ScreenType => ScreenTypes.Report;

		public FixedAssetListReport()
		{
			InitializeComponent();
			base.Load += Form_Load;
		}

		private void Form_Load(object sender, EventArgs e)
		{
			try
			{
				SetSecurity();
				_ = base.IsDisposed;
			}
			catch (Exception e2)
			{
				ErrorHelper.ProcessError(e2);
			}
		}

		private void SetSecurity()
		{
			screenRight = Security.GetScreenAccessRight(base.Name);
			if (!screenRight.View)
			{
				ErrorHelper.ErrorMessage(UIMessages.NoPermissionView);
				Close();
			}
		}

		private void buttonOK_Click(object sender, EventArgs e)
		{
			DataSet data = Factory.FixedAssetSystem.GetAssetListReport(FixedAssetSelector.FromFixedAsset, FixedAssetSelector.ToFixedAsset, FixedAssetSelector.FromClass, FixedAssetSelector.ToClass, FixedAssetSelector.FromGroup, FixedAssetSelector.ToGroup, FixedAssetSelector.FromLocation, FixedAssetSelector.ToLocation, comboBoxFromDivision.SelectedID, comboBoxToDivision.SelectedID, comboBoxFromDepartment.SelectedID, comboBoxToDepartment.SelectedID, comboBoxCountryFrom.SelectedID, comboBoxCountryTo.SelectedID, ComboBoxCompanyFrom.SelectedID, ComboBoxCompanyTo.SelectedID, checkBoxShowInactive.Checked);
			ReportHelper reportHelper = new ReportHelper();
			string reportFilter = "";
			reportHelper.AddGeneralReportData(ref data, reportFilter);
			reportHelper.AddFilterData(ref data, GetAllFormControls(this));
			XtraReport report = reportHelper.GetReport("Fixed Asset List");
			if (report == null)
			{
				ErrorHelper.ErrorMessage("Cannot find the report file", "'Fixed Asset List.repx'", "Please make sure you have access to reports path and the files are not corrupted.");
				return;
			}
			report.DataSource = data;
			reportHelper.ShowReport(report);
		}

		public IEnumerable<Control> GetAllFormControls(Control control)
		{
			IEnumerable<Control> controls = control.Controls.Cast<Control>();
			return controls.SelectMany((Control ctrl) => GetAllFormControls(ctrl).Concat(controls));
		}

		private void buttonClose_Click(object sender, EventArgs e)
		{
			Close();
		}

		private void fixedAssetSelector1_Load(object sender, EventArgs e)
		{
		}

		private void radioButtonDivision_CheckedChanged(object sender, EventArgs e)
		{
		}

		private void radioButtonDepartment_CheckedChanged(object sender, EventArgs e)
		{
		}

		private void radioButtons_CheckedChanged(object sender, EventArgs e)
		{
			EnableDisableControls();
		}

		private void EnableDisableControls()
		{
			DivisionComboBox divisionComboBox = comboBoxFromDivision;
			bool enabled = comboBoxToDivision.Enabled = radioButtonDivision.Checked;
			divisionComboBox.Enabled = enabled;
			DepartmentComboBox departmentComboBox = comboBoxFromDepartment;
			enabled = (comboBoxToDepartment.Enabled = radioButtonDepartment.Checked);
			departmentComboBox.Enabled = enabled;
			GenericListComboBox comboBoxCompanyFrom = ComboBoxCompanyFrom;
			enabled = (ComboBoxCompanyTo.Enabled = radioButtoncompany.Checked);
			comboBoxCompanyFrom.Enabled = enabled;
			CountryComboBox countryComboBox = comboBoxCountryFrom;
			enabled = (comboBoxCountryTo.Enabled = radioButtoncountry.Checked);
			countryComboBox.Enabled = enabled;
		}

		private void radioButtoncountry_CheckedChanged(object sender, EventArgs e)
		{
		}

		private void radioButtoncompany_CheckedChanged(object sender, EventArgs e)
		{
		}

		private void InitializeComponent()
		{
			Infragistics.Win.Appearance appearance = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance39 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance40 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance41 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance42 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance43 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance44 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance45 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance46 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance47 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance48 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance49 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance50 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance51 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance52 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance53 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance54 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance55 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance56 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance57 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance58 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance59 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance60 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance61 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance62 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance63 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance64 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance65 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance66 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance67 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance68 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance69 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance70 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance71 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance72 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance73 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance74 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance75 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance76 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance77 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance78 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance79 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance80 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance81 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance82 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance83 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance84 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance85 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance86 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance87 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance88 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance89 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance90 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance91 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance92 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance93 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance94 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance95 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance96 = new Infragistics.Win.Appearance();
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Micromind.ClientUI.Reports.Customers.FixedAssetListReport));
			buttonOK = new System.Windows.Forms.Button();
			checkBoxShowInactive = new System.Windows.Forms.CheckBox();
			buttonClose = new System.Windows.Forms.Button();
			FixedAssetSelector = new Micromind.DataControls.FixedAssetSelector();
			radioButtonDivision = new System.Windows.Forms.RadioButton();
			label6 = new System.Windows.Forms.Label();
			label1 = new System.Windows.Forms.Label();
			label7 = new System.Windows.Forms.Label();
			label2 = new System.Windows.Forms.Label();
			radioButtonDepartment = new System.Windows.Forms.RadioButton();
			ultraGroupBox1 = new Infragistics.Win.Misc.UltraGroupBox();
			comboBoxFromDivision = new Micromind.DataControls.DivisionComboBox();
			comboBoxToDivision = new Micromind.DataControls.DivisionComboBox();
			comboBoxFromDepartment = new Micromind.DataControls.DepartmentComboBox();
			comboBoxToDepartment = new Micromind.DataControls.DepartmentComboBox();
			radioButtoncountry = new System.Windows.Forms.RadioButton();
			radioButtoncompany = new System.Windows.Forms.RadioButton();
			label3 = new System.Windows.Forms.Label();
			label4 = new System.Windows.Forms.Label();
			label5 = new System.Windows.Forms.Label();
			label8 = new System.Windows.Forms.Label();
			ComboBoxCompanyFrom = new Micromind.DataControls.GenericListComboBox();
			ComboBoxCompanyTo = new Micromind.DataControls.GenericListComboBox();
			comboBoxCountryFrom = new Micromind.DataControls.CountryComboBox();
			comboBoxCountryTo = new Micromind.DataControls.CountryComboBox();
			((System.ComponentModel.ISupportInitialize)ultraGroupBox1).BeginInit();
			ultraGroupBox1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)comboBoxFromDivision).BeginInit();
			((System.ComponentModel.ISupportInitialize)comboBoxToDivision).BeginInit();
			((System.ComponentModel.ISupportInitialize)comboBoxFromDepartment).BeginInit();
			((System.ComponentModel.ISupportInitialize)comboBoxToDepartment).BeginInit();
			((System.ComponentModel.ISupportInitialize)ComboBoxCompanyFrom).BeginInit();
			((System.ComponentModel.ISupportInitialize)ComboBoxCompanyTo).BeginInit();
			((System.ComponentModel.ISupportInitialize)comboBoxCountryFrom).BeginInit();
			((System.ComponentModel.ISupportInitialize)comboBoxCountryTo).BeginInit();
			SuspendLayout();
			buttonOK.Anchor = (System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right);
			buttonOK.Location = new System.Drawing.Point(266, 282);
			buttonOK.Name = "buttonOK";
			buttonOK.Size = new System.Drawing.Size(98, 24);
			buttonOK.TabIndex = 1;
			buttonOK.Text = "&Display";
			buttonOK.UseVisualStyleBackColor = true;
			buttonOK.Click += new System.EventHandler(buttonOK_Click);
			checkBoxShowInactive.AutoSize = true;
			checkBoxShowInactive.Location = new System.Drawing.Point(19, 270);
			checkBoxShowInactive.Name = "checkBoxShowInactive";
			checkBoxShowInactive.Size = new System.Drawing.Size(96, 17);
			checkBoxShowInactive.TabIndex = 4;
			checkBoxShowInactive.Text = "Show inactive ";
			checkBoxShowInactive.UseVisualStyleBackColor = true;
			checkBoxShowInactive.Visible = false;
			buttonClose.Anchor = (System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right);
			buttonClose.DialogResult = System.Windows.Forms.DialogResult.Cancel;
			buttonClose.Location = new System.Drawing.Point(370, 282);
			buttonClose.Name = "buttonClose";
			buttonClose.Size = new System.Drawing.Size(98, 24);
			buttonClose.TabIndex = 5;
			buttonClose.Text = "&Close";
			buttonClose.UseVisualStyleBackColor = true;
			buttonClose.Click += new System.EventHandler(buttonClose_Click);
			FixedAssetSelector.BackColor = System.Drawing.Color.Transparent;
			FixedAssetSelector.CustomReportFieldName = "";
			FixedAssetSelector.CustomReportKey = "";
			FixedAssetSelector.CustomReportValueType = 1;
			FixedAssetSelector.Location = new System.Drawing.Point(10, 17);
			FixedAssetSelector.Name = "FixedAssetSelector";
			FixedAssetSelector.Size = new System.Drawing.Size(436, 122);
			FixedAssetSelector.TabIndex = 0;
			radioButtonDivision.AutoSize = true;
			radioButtonDivision.Location = new System.Drawing.Point(31, 160);
			radioButtonDivision.Name = "radioButtonDivision";
			radioButtonDivision.Size = new System.Drawing.Size(63, 17);
			radioButtonDivision.TabIndex = 13;
			radioButtonDivision.Text = "Divsion:";
			radioButtonDivision.UseVisualStyleBackColor = true;
			radioButtonDivision.CheckedChanged += new System.EventHandler(radioButtons_CheckedChanged);
			label6.AutoSize = true;
			label6.Location = new System.Drawing.Point(162, 186);
			label6.Name = "label6";
			label6.Size = new System.Drawing.Size(33, 13);
			label6.TabIndex = 16;
			label6.Text = "From:";
			label1.AutoSize = true;
			label1.Location = new System.Drawing.Point(161, 164);
			label1.Name = "label1";
			label1.Size = new System.Drawing.Size(33, 13);
			label1.TabIndex = 17;
			label1.Text = "From:";
			label7.AutoSize = true;
			label7.Location = new System.Drawing.Point(317, 164);
			label7.Name = "label7";
			label7.Size = new System.Drawing.Size(23, 13);
			label7.TabIndex = 18;
			label7.Text = "To:";
			label2.AutoSize = true;
			label2.Location = new System.Drawing.Point(317, 186);
			label2.Name = "label2";
			label2.Size = new System.Drawing.Size(23, 13);
			label2.TabIndex = 19;
			label2.Text = "To:";
			radioButtonDepartment.AutoSize = true;
			radioButtonDepartment.Location = new System.Drawing.Point(32, 181);
			radioButtonDepartment.Name = "radioButtonDepartment";
			radioButtonDepartment.Size = new System.Drawing.Size(83, 17);
			radioButtonDepartment.TabIndex = 22;
			radioButtonDepartment.Text = "Department:";
			radioButtonDepartment.UseVisualStyleBackColor = true;
			radioButtonDepartment.CheckedChanged += new System.EventHandler(radioButtons_CheckedChanged);
			ultraGroupBox1.Controls.Add(FixedAssetSelector);
			ultraGroupBox1.Location = new System.Drawing.Point(12, 12);
			ultraGroupBox1.Name = "ultraGroupBox1";
			ultraGroupBox1.Size = new System.Drawing.Size(448, 139);
			ultraGroupBox1.TabIndex = 3;
			ultraGroupBox1.Text = "Fixed Asset";
			comboBoxFromDivision.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			comboBoxFromDivision.CustomReportFieldName = "";
			comboBoxFromDivision.CustomReportKey = "";
			comboBoxFromDivision.CustomReportValueType = 1;
			comboBoxFromDivision.DescriptionTextBox = null;
			appearance.BackColor = System.Drawing.SystemColors.Window;
			appearance.BorderColor = System.Drawing.SystemColors.InactiveCaption;
			comboBoxFromDivision.DisplayLayout.Appearance = appearance;
			comboBoxFromDivision.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
			comboBoxFromDivision.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
			appearance2.BackColor = System.Drawing.SystemColors.ActiveBorder;
			appearance2.BackColor2 = System.Drawing.SystemColors.ControlDark;
			appearance2.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
			appearance2.BorderColor = System.Drawing.SystemColors.Window;
			comboBoxFromDivision.DisplayLayout.GroupByBox.Appearance = appearance2;
			appearance3.ForeColor = System.Drawing.SystemColors.GrayText;
			comboBoxFromDivision.DisplayLayout.GroupByBox.BandLabelAppearance = appearance3;
			comboBoxFromDivision.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
			appearance4.BackColor = System.Drawing.SystemColors.ControlLightLight;
			appearance4.BackColor2 = System.Drawing.SystemColors.Control;
			appearance4.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
			appearance4.ForeColor = System.Drawing.SystemColors.GrayText;
			comboBoxFromDivision.DisplayLayout.GroupByBox.PromptAppearance = appearance4;
			comboBoxFromDivision.DisplayLayout.MaxColScrollRegions = 1;
			comboBoxFromDivision.DisplayLayout.MaxRowScrollRegions = 1;
			appearance5.BackColor = System.Drawing.SystemColors.Window;
			appearance5.ForeColor = System.Drawing.SystemColors.ControlText;
			comboBoxFromDivision.DisplayLayout.Override.ActiveCellAppearance = appearance5;
			appearance6.BackColor = System.Drawing.SystemColors.Highlight;
			appearance6.ForeColor = System.Drawing.SystemColors.HighlightText;
			comboBoxFromDivision.DisplayLayout.Override.ActiveRowAppearance = appearance6;
			comboBoxFromDivision.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
			comboBoxFromDivision.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
			appearance7.BackColor = System.Drawing.SystemColors.Window;
			comboBoxFromDivision.DisplayLayout.Override.CardAreaAppearance = appearance7;
			appearance8.BorderColor = System.Drawing.Color.Silver;
			appearance8.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
			comboBoxFromDivision.DisplayLayout.Override.CellAppearance = appearance8;
			comboBoxFromDivision.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
			comboBoxFromDivision.DisplayLayout.Override.CellPadding = 0;
			appearance9.BackColor = System.Drawing.SystemColors.Control;
			appearance9.BackColor2 = System.Drawing.SystemColors.ControlDark;
			appearance9.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
			appearance9.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
			appearance9.BorderColor = System.Drawing.SystemColors.Window;
			comboBoxFromDivision.DisplayLayout.Override.GroupByRowAppearance = appearance9;
			appearance10.TextHAlignAsString = "Left";
			comboBoxFromDivision.DisplayLayout.Override.HeaderAppearance = appearance10;
			comboBoxFromDivision.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
			comboBoxFromDivision.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
			appearance11.BackColor = System.Drawing.SystemColors.Window;
			appearance11.BorderColor = System.Drawing.Color.Silver;
			comboBoxFromDivision.DisplayLayout.Override.RowAppearance = appearance11;
			comboBoxFromDivision.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
			appearance12.BackColor = System.Drawing.SystemColors.ControlLight;
			comboBoxFromDivision.DisplayLayout.Override.TemplateAddRowAppearance = appearance12;
			comboBoxFromDivision.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
			comboBoxFromDivision.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
			comboBoxFromDivision.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
			comboBoxFromDivision.DropDownSearchMethod = Infragistics.Win.UltraWinGrid.DropDownSearchMethod.Linear;
			comboBoxFromDivision.Editable = true;
			comboBoxFromDivision.FilterString = "";
			comboBoxFromDivision.HasAllAccount = false;
			comboBoxFromDivision.HasCustom = false;
			comboBoxFromDivision.IsDataLoaded = false;
			comboBoxFromDivision.Location = new System.Drawing.Point(203, 157);
			comboBoxFromDivision.MaxDropDownItems = 12;
			comboBoxFromDivision.Name = "comboBoxFromDivision";
			comboBoxFromDivision.ShowInactiveItems = false;
			comboBoxFromDivision.ShowQuickAdd = true;
			comboBoxFromDivision.Size = new System.Drawing.Size(110, 20);
			comboBoxFromDivision.TabIndex = 14;
			comboBoxFromDivision.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
			comboBoxToDivision.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			comboBoxToDivision.CustomReportFieldName = "";
			comboBoxToDivision.CustomReportKey = "";
			comboBoxToDivision.CustomReportValueType = 1;
			comboBoxToDivision.DescriptionTextBox = null;
			appearance13.BackColor = System.Drawing.SystemColors.Window;
			appearance13.BorderColor = System.Drawing.SystemColors.InactiveCaption;
			comboBoxToDivision.DisplayLayout.Appearance = appearance13;
			comboBoxToDivision.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
			comboBoxToDivision.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
			appearance14.BackColor = System.Drawing.SystemColors.ActiveBorder;
			appearance14.BackColor2 = System.Drawing.SystemColors.ControlDark;
			appearance14.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
			appearance14.BorderColor = System.Drawing.SystemColors.Window;
			comboBoxToDivision.DisplayLayout.GroupByBox.Appearance = appearance14;
			appearance15.ForeColor = System.Drawing.SystemColors.GrayText;
			comboBoxToDivision.DisplayLayout.GroupByBox.BandLabelAppearance = appearance15;
			comboBoxToDivision.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
			appearance16.BackColor = System.Drawing.SystemColors.ControlLightLight;
			appearance16.BackColor2 = System.Drawing.SystemColors.Control;
			appearance16.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
			appearance16.ForeColor = System.Drawing.SystemColors.GrayText;
			comboBoxToDivision.DisplayLayout.GroupByBox.PromptAppearance = appearance16;
			comboBoxToDivision.DisplayLayout.MaxColScrollRegions = 1;
			comboBoxToDivision.DisplayLayout.MaxRowScrollRegions = 1;
			appearance17.BackColor = System.Drawing.SystemColors.Window;
			appearance17.ForeColor = System.Drawing.SystemColors.ControlText;
			comboBoxToDivision.DisplayLayout.Override.ActiveCellAppearance = appearance17;
			appearance18.BackColor = System.Drawing.SystemColors.Highlight;
			appearance18.ForeColor = System.Drawing.SystemColors.HighlightText;
			comboBoxToDivision.DisplayLayout.Override.ActiveRowAppearance = appearance18;
			comboBoxToDivision.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
			comboBoxToDivision.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
			appearance19.BackColor = System.Drawing.SystemColors.Window;
			comboBoxToDivision.DisplayLayout.Override.CardAreaAppearance = appearance19;
			appearance20.BorderColor = System.Drawing.Color.Silver;
			appearance20.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
			comboBoxToDivision.DisplayLayout.Override.CellAppearance = appearance20;
			comboBoxToDivision.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
			comboBoxToDivision.DisplayLayout.Override.CellPadding = 0;
			appearance21.BackColor = System.Drawing.SystemColors.Control;
			appearance21.BackColor2 = System.Drawing.SystemColors.ControlDark;
			appearance21.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
			appearance21.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
			appearance21.BorderColor = System.Drawing.SystemColors.Window;
			comboBoxToDivision.DisplayLayout.Override.GroupByRowAppearance = appearance21;
			appearance22.TextHAlignAsString = "Left";
			comboBoxToDivision.DisplayLayout.Override.HeaderAppearance = appearance22;
			comboBoxToDivision.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
			comboBoxToDivision.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
			appearance23.BackColor = System.Drawing.SystemColors.Window;
			appearance23.BorderColor = System.Drawing.Color.Silver;
			comboBoxToDivision.DisplayLayout.Override.RowAppearance = appearance23;
			comboBoxToDivision.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
			appearance24.BackColor = System.Drawing.SystemColors.ControlLight;
			comboBoxToDivision.DisplayLayout.Override.TemplateAddRowAppearance = appearance24;
			comboBoxToDivision.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
			comboBoxToDivision.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
			comboBoxToDivision.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
			comboBoxToDivision.DropDownSearchMethod = Infragistics.Win.UltraWinGrid.DropDownSearchMethod.Linear;
			comboBoxToDivision.Editable = true;
			comboBoxToDivision.FilterString = "";
			comboBoxToDivision.HasAllAccount = false;
			comboBoxToDivision.HasCustom = false;
			comboBoxToDivision.IsDataLoaded = false;
			comboBoxToDivision.Location = new System.Drawing.Point(340, 157);
			comboBoxToDivision.MaxDropDownItems = 12;
			comboBoxToDivision.Name = "comboBoxToDivision";
			comboBoxToDivision.ShowInactiveItems = false;
			comboBoxToDivision.ShowQuickAdd = true;
			comboBoxToDivision.Size = new System.Drawing.Size(106, 20);
			comboBoxToDivision.TabIndex = 15;
			comboBoxToDivision.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
			comboBoxFromDepartment.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			comboBoxFromDepartment.CustomReportFieldName = "";
			comboBoxFromDepartment.CustomReportKey = "";
			comboBoxFromDepartment.CustomReportValueType = 1;
			comboBoxFromDepartment.DescriptionTextBox = null;
			appearance25.BackColor = System.Drawing.SystemColors.Window;
			appearance25.BorderColor = System.Drawing.SystemColors.InactiveCaption;
			comboBoxFromDepartment.DisplayLayout.Appearance = appearance25;
			comboBoxFromDepartment.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
			comboBoxFromDepartment.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
			appearance26.BackColor = System.Drawing.SystemColors.ActiveBorder;
			appearance26.BackColor2 = System.Drawing.SystemColors.ControlDark;
			appearance26.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
			appearance26.BorderColor = System.Drawing.SystemColors.Window;
			comboBoxFromDepartment.DisplayLayout.GroupByBox.Appearance = appearance26;
			appearance27.ForeColor = System.Drawing.SystemColors.GrayText;
			comboBoxFromDepartment.DisplayLayout.GroupByBox.BandLabelAppearance = appearance27;
			comboBoxFromDepartment.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
			appearance28.BackColor = System.Drawing.SystemColors.ControlLightLight;
			appearance28.BackColor2 = System.Drawing.SystemColors.Control;
			appearance28.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
			appearance28.ForeColor = System.Drawing.SystemColors.GrayText;
			comboBoxFromDepartment.DisplayLayout.GroupByBox.PromptAppearance = appearance28;
			comboBoxFromDepartment.DisplayLayout.MaxColScrollRegions = 1;
			comboBoxFromDepartment.DisplayLayout.MaxRowScrollRegions = 1;
			appearance29.BackColor = System.Drawing.SystemColors.Window;
			appearance29.ForeColor = System.Drawing.SystemColors.ControlText;
			comboBoxFromDepartment.DisplayLayout.Override.ActiveCellAppearance = appearance29;
			appearance30.BackColor = System.Drawing.SystemColors.Highlight;
			appearance30.ForeColor = System.Drawing.SystemColors.HighlightText;
			comboBoxFromDepartment.DisplayLayout.Override.ActiveRowAppearance = appearance30;
			comboBoxFromDepartment.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
			comboBoxFromDepartment.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
			appearance31.BackColor = System.Drawing.SystemColors.Window;
			comboBoxFromDepartment.DisplayLayout.Override.CardAreaAppearance = appearance31;
			appearance32.BorderColor = System.Drawing.Color.Silver;
			appearance32.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
			comboBoxFromDepartment.DisplayLayout.Override.CellAppearance = appearance32;
			comboBoxFromDepartment.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
			comboBoxFromDepartment.DisplayLayout.Override.CellPadding = 0;
			appearance33.BackColor = System.Drawing.SystemColors.Control;
			appearance33.BackColor2 = System.Drawing.SystemColors.ControlDark;
			appearance33.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
			appearance33.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
			appearance33.BorderColor = System.Drawing.SystemColors.Window;
			comboBoxFromDepartment.DisplayLayout.Override.GroupByRowAppearance = appearance33;
			appearance34.TextHAlignAsString = "Left";
			comboBoxFromDepartment.DisplayLayout.Override.HeaderAppearance = appearance34;
			comboBoxFromDepartment.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
			comboBoxFromDepartment.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
			appearance35.BackColor = System.Drawing.SystemColors.Window;
			appearance35.BorderColor = System.Drawing.Color.Silver;
			comboBoxFromDepartment.DisplayLayout.Override.RowAppearance = appearance35;
			comboBoxFromDepartment.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
			appearance36.BackColor = System.Drawing.SystemColors.ControlLight;
			comboBoxFromDepartment.DisplayLayout.Override.TemplateAddRowAppearance = appearance36;
			comboBoxFromDepartment.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
			comboBoxFromDepartment.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
			comboBoxFromDepartment.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
			comboBoxFromDepartment.DropDownSearchMethod = Infragistics.Win.UltraWinGrid.DropDownSearchMethod.Linear;
			comboBoxFromDepartment.Editable = true;
			comboBoxFromDepartment.FilterString = "";
			comboBoxFromDepartment.HasAllAccount = false;
			comboBoxFromDepartment.HasCustom = false;
			comboBoxFromDepartment.IsDataLoaded = false;
			comboBoxFromDepartment.Location = new System.Drawing.Point(202, 181);
			comboBoxFromDepartment.MaxDropDownItems = 12;
			comboBoxFromDepartment.Name = "comboBoxFromDepartment";
			comboBoxFromDepartment.ShowInactiveItems = false;
			comboBoxFromDepartment.ShowQuickAdd = true;
			comboBoxFromDepartment.Size = new System.Drawing.Size(110, 20);
			comboBoxFromDepartment.TabIndex = 20;
			comboBoxFromDepartment.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
			comboBoxToDepartment.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			comboBoxToDepartment.CustomReportFieldName = "";
			comboBoxToDepartment.CustomReportKey = "";
			comboBoxToDepartment.CustomReportValueType = 1;
			comboBoxToDepartment.DescriptionTextBox = null;
			appearance37.BackColor = System.Drawing.SystemColors.Window;
			appearance37.BorderColor = System.Drawing.SystemColors.InactiveCaption;
			comboBoxToDepartment.DisplayLayout.Appearance = appearance37;
			comboBoxToDepartment.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
			comboBoxToDepartment.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
			appearance38.BackColor = System.Drawing.SystemColors.ActiveBorder;
			appearance38.BackColor2 = System.Drawing.SystemColors.ControlDark;
			appearance38.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
			appearance38.BorderColor = System.Drawing.SystemColors.Window;
			comboBoxToDepartment.DisplayLayout.GroupByBox.Appearance = appearance38;
			appearance39.ForeColor = System.Drawing.SystemColors.GrayText;
			comboBoxToDepartment.DisplayLayout.GroupByBox.BandLabelAppearance = appearance39;
			comboBoxToDepartment.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
			appearance40.BackColor = System.Drawing.SystemColors.ControlLightLight;
			appearance40.BackColor2 = System.Drawing.SystemColors.Control;
			appearance40.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
			appearance40.ForeColor = System.Drawing.SystemColors.GrayText;
			comboBoxToDepartment.DisplayLayout.GroupByBox.PromptAppearance = appearance40;
			comboBoxToDepartment.DisplayLayout.MaxColScrollRegions = 1;
			comboBoxToDepartment.DisplayLayout.MaxRowScrollRegions = 1;
			appearance41.BackColor = System.Drawing.SystemColors.Window;
			appearance41.ForeColor = System.Drawing.SystemColors.ControlText;
			comboBoxToDepartment.DisplayLayout.Override.ActiveCellAppearance = appearance41;
			appearance42.BackColor = System.Drawing.SystemColors.Highlight;
			appearance42.ForeColor = System.Drawing.SystemColors.HighlightText;
			comboBoxToDepartment.DisplayLayout.Override.ActiveRowAppearance = appearance42;
			comboBoxToDepartment.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
			comboBoxToDepartment.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
			appearance43.BackColor = System.Drawing.SystemColors.Window;
			comboBoxToDepartment.DisplayLayout.Override.CardAreaAppearance = appearance43;
			appearance44.BorderColor = System.Drawing.Color.Silver;
			appearance44.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
			comboBoxToDepartment.DisplayLayout.Override.CellAppearance = appearance44;
			comboBoxToDepartment.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
			comboBoxToDepartment.DisplayLayout.Override.CellPadding = 0;
			appearance45.BackColor = System.Drawing.SystemColors.Control;
			appearance45.BackColor2 = System.Drawing.SystemColors.ControlDark;
			appearance45.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
			appearance45.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
			appearance45.BorderColor = System.Drawing.SystemColors.Window;
			comboBoxToDepartment.DisplayLayout.Override.GroupByRowAppearance = appearance45;
			appearance46.TextHAlignAsString = "Left";
			comboBoxToDepartment.DisplayLayout.Override.HeaderAppearance = appearance46;
			comboBoxToDepartment.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
			comboBoxToDepartment.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
			appearance47.BackColor = System.Drawing.SystemColors.Window;
			appearance47.BorderColor = System.Drawing.Color.Silver;
			comboBoxToDepartment.DisplayLayout.Override.RowAppearance = appearance47;
			comboBoxToDepartment.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
			appearance48.BackColor = System.Drawing.SystemColors.ControlLight;
			comboBoxToDepartment.DisplayLayout.Override.TemplateAddRowAppearance = appearance48;
			comboBoxToDepartment.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
			comboBoxToDepartment.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
			comboBoxToDepartment.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
			comboBoxToDepartment.DropDownSearchMethod = Infragistics.Win.UltraWinGrid.DropDownSearchMethod.Linear;
			comboBoxToDepartment.Editable = true;
			comboBoxToDepartment.FilterString = "";
			comboBoxToDepartment.HasAllAccount = false;
			comboBoxToDepartment.HasCustom = false;
			comboBoxToDepartment.IsDataLoaded = false;
			comboBoxToDepartment.Location = new System.Drawing.Point(340, 181);
			comboBoxToDepartment.MaxDropDownItems = 12;
			comboBoxToDepartment.Name = "comboBoxToDepartment";
			comboBoxToDepartment.ShowInactiveItems = false;
			comboBoxToDepartment.ShowQuickAdd = true;
			comboBoxToDepartment.Size = new System.Drawing.Size(106, 20);
			comboBoxToDepartment.TabIndex = 21;
			comboBoxToDepartment.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
			radioButtoncountry.AutoSize = true;
			radioButtoncountry.Location = new System.Drawing.Point(32, 215);
			radioButtoncountry.Name = "radioButtoncountry";
			radioButtoncountry.Size = new System.Drawing.Size(64, 17);
			radioButtoncountry.TabIndex = 23;
			radioButtoncountry.Text = "Country:";
			radioButtoncountry.UseVisualStyleBackColor = true;
			radioButtoncountry.CheckedChanged += new System.EventHandler(radioButtons_CheckedChanged);
			radioButtoncompany.AutoSize = true;
			radioButtoncompany.Location = new System.Drawing.Point(32, 238);
			radioButtoncompany.Name = "radioButtoncompany";
			radioButtoncompany.Size = new System.Drawing.Size(75, 17);
			radioButtoncompany.TabIndex = 24;
			radioButtoncompany.Text = "Company :";
			radioButtoncompany.UseVisualStyleBackColor = true;
			radioButtoncompany.CheckedChanged += new System.EventHandler(radioButtons_CheckedChanged);
			label3.AutoSize = true;
			label3.Location = new System.Drawing.Point(162, 219);
			label3.Name = "label3";
			label3.Size = new System.Drawing.Size(33, 13);
			label3.TabIndex = 25;
			label3.Text = "From:";
			label4.AutoSize = true;
			label4.Location = new System.Drawing.Point(161, 242);
			label4.Name = "label4";
			label4.Size = new System.Drawing.Size(33, 13);
			label4.TabIndex = 26;
			label4.Text = "From:";
			label5.AutoSize = true;
			label5.Location = new System.Drawing.Point(317, 215);
			label5.Name = "label5";
			label5.Size = new System.Drawing.Size(23, 13);
			label5.TabIndex = 27;
			label5.Text = "To:";
			label8.AutoSize = true;
			label8.Location = new System.Drawing.Point(317, 240);
			label8.Name = "label8";
			label8.Size = new System.Drawing.Size(23, 13);
			label8.TabIndex = 28;
			label8.Text = "To:";
			ComboBoxCompanyFrom.AutoCompleteMode = Infragistics.Win.AutoCompleteMode.Append;
			ComboBoxCompanyFrom.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			ComboBoxCompanyFrom.CustomReportFieldName = "";
			ComboBoxCompanyFrom.CustomReportKey = "";
			ComboBoxCompanyFrom.CustomReportValueType = 1;
			ComboBoxCompanyFrom.DescriptionTextBox = null;
			appearance49.BackColor = System.Drawing.SystemColors.Window;
			appearance49.BorderColor = System.Drawing.SystemColors.InactiveCaption;
			ComboBoxCompanyFrom.DisplayLayout.Appearance = appearance49;
			ComboBoxCompanyFrom.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
			ComboBoxCompanyFrom.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
			appearance50.BackColor = System.Drawing.SystemColors.ActiveBorder;
			appearance50.BackColor2 = System.Drawing.SystemColors.ControlDark;
			appearance50.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
			appearance50.BorderColor = System.Drawing.SystemColors.Window;
			ComboBoxCompanyFrom.DisplayLayout.GroupByBox.Appearance = appearance50;
			appearance51.ForeColor = System.Drawing.SystemColors.GrayText;
			ComboBoxCompanyFrom.DisplayLayout.GroupByBox.BandLabelAppearance = appearance51;
			ComboBoxCompanyFrom.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
			appearance52.BackColor = System.Drawing.SystemColors.ControlLightLight;
			appearance52.BackColor2 = System.Drawing.SystemColors.Control;
			appearance52.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
			appearance52.ForeColor = System.Drawing.SystemColors.GrayText;
			ComboBoxCompanyFrom.DisplayLayout.GroupByBox.PromptAppearance = appearance52;
			ComboBoxCompanyFrom.DisplayLayout.MaxColScrollRegions = 1;
			ComboBoxCompanyFrom.DisplayLayout.MaxRowScrollRegions = 1;
			appearance53.BackColor = System.Drawing.SystemColors.Window;
			appearance53.ForeColor = System.Drawing.SystemColors.ControlText;
			ComboBoxCompanyFrom.DisplayLayout.Override.ActiveCellAppearance = appearance53;
			appearance54.BackColor = System.Drawing.SystemColors.Highlight;
			appearance54.ForeColor = System.Drawing.SystemColors.HighlightText;
			ComboBoxCompanyFrom.DisplayLayout.Override.ActiveRowAppearance = appearance54;
			ComboBoxCompanyFrom.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
			ComboBoxCompanyFrom.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
			appearance55.BackColor = System.Drawing.SystemColors.Window;
			ComboBoxCompanyFrom.DisplayLayout.Override.CardAreaAppearance = appearance55;
			appearance56.BorderColor = System.Drawing.Color.Silver;
			appearance56.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
			ComboBoxCompanyFrom.DisplayLayout.Override.CellAppearance = appearance56;
			ComboBoxCompanyFrom.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
			ComboBoxCompanyFrom.DisplayLayout.Override.CellPadding = 0;
			appearance57.BackColor = System.Drawing.SystemColors.Control;
			appearance57.BackColor2 = System.Drawing.SystemColors.ControlDark;
			appearance57.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
			appearance57.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
			appearance57.BorderColor = System.Drawing.SystemColors.Window;
			ComboBoxCompanyFrom.DisplayLayout.Override.GroupByRowAppearance = appearance57;
			appearance58.TextHAlignAsString = "Left";
			ComboBoxCompanyFrom.DisplayLayout.Override.HeaderAppearance = appearance58;
			ComboBoxCompanyFrom.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
			ComboBoxCompanyFrom.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
			appearance59.BackColor = System.Drawing.SystemColors.Window;
			appearance59.BorderColor = System.Drawing.Color.Silver;
			ComboBoxCompanyFrom.DisplayLayout.Override.RowAppearance = appearance59;
			ComboBoxCompanyFrom.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
			appearance60.BackColor = System.Drawing.SystemColors.ControlLight;
			ComboBoxCompanyFrom.DisplayLayout.Override.TemplateAddRowAppearance = appearance60;
			ComboBoxCompanyFrom.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
			ComboBoxCompanyFrom.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
			ComboBoxCompanyFrom.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
			ComboBoxCompanyFrom.DropDownSearchMethod = Infragistics.Win.UltraWinGrid.DropDownSearchMethod.Linear;
			ComboBoxCompanyFrom.Editable = true;
			ComboBoxCompanyFrom.FilterString = "";
			ComboBoxCompanyFrom.GenericListType = Micromind.Common.Data.GenericListTypes.FixedAssetCompany;
			ComboBoxCompanyFrom.HasAllAccount = false;
			ComboBoxCompanyFrom.HasCustom = false;
			ComboBoxCompanyFrom.IsDataLoaded = false;
			ComboBoxCompanyFrom.IsSingleColumn = false;
			ComboBoxCompanyFrom.Location = new System.Drawing.Point(203, 238);
			ComboBoxCompanyFrom.MaxDropDownItems = 12;
			ComboBoxCompanyFrom.Name = "ComboBoxCompanyFrom";
			ComboBoxCompanyFrom.ShowInactiveItems = false;
			ComboBoxCompanyFrom.ShowQuickAdd = true;
			ComboBoxCompanyFrom.Size = new System.Drawing.Size(110, 20);
			ComboBoxCompanyFrom.TabIndex = 29;
			ComboBoxCompanyFrom.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
			ComboBoxCompanyTo.AutoCompleteMode = Infragistics.Win.AutoCompleteMode.Append;
			ComboBoxCompanyTo.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			ComboBoxCompanyTo.CustomReportFieldName = "";
			ComboBoxCompanyTo.CustomReportKey = "";
			ComboBoxCompanyTo.CustomReportValueType = 1;
			ComboBoxCompanyTo.DescriptionTextBox = null;
			appearance61.BackColor = System.Drawing.SystemColors.Window;
			appearance61.BorderColor = System.Drawing.SystemColors.InactiveCaption;
			ComboBoxCompanyTo.DisplayLayout.Appearance = appearance61;
			ComboBoxCompanyTo.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
			ComboBoxCompanyTo.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
			appearance62.BackColor = System.Drawing.SystemColors.ActiveBorder;
			appearance62.BackColor2 = System.Drawing.SystemColors.ControlDark;
			appearance62.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
			appearance62.BorderColor = System.Drawing.SystemColors.Window;
			ComboBoxCompanyTo.DisplayLayout.GroupByBox.Appearance = appearance62;
			appearance63.ForeColor = System.Drawing.SystemColors.GrayText;
			ComboBoxCompanyTo.DisplayLayout.GroupByBox.BandLabelAppearance = appearance63;
			ComboBoxCompanyTo.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
			appearance64.BackColor = System.Drawing.SystemColors.ControlLightLight;
			appearance64.BackColor2 = System.Drawing.SystemColors.Control;
			appearance64.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
			appearance64.ForeColor = System.Drawing.SystemColors.GrayText;
			ComboBoxCompanyTo.DisplayLayout.GroupByBox.PromptAppearance = appearance64;
			ComboBoxCompanyTo.DisplayLayout.MaxColScrollRegions = 1;
			ComboBoxCompanyTo.DisplayLayout.MaxRowScrollRegions = 1;
			appearance65.BackColor = System.Drawing.SystemColors.Window;
			appearance65.ForeColor = System.Drawing.SystemColors.ControlText;
			ComboBoxCompanyTo.DisplayLayout.Override.ActiveCellAppearance = appearance65;
			appearance66.BackColor = System.Drawing.SystemColors.Highlight;
			appearance66.ForeColor = System.Drawing.SystemColors.HighlightText;
			ComboBoxCompanyTo.DisplayLayout.Override.ActiveRowAppearance = appearance66;
			ComboBoxCompanyTo.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
			ComboBoxCompanyTo.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
			appearance67.BackColor = System.Drawing.SystemColors.Window;
			ComboBoxCompanyTo.DisplayLayout.Override.CardAreaAppearance = appearance67;
			appearance68.BorderColor = System.Drawing.Color.Silver;
			appearance68.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
			ComboBoxCompanyTo.DisplayLayout.Override.CellAppearance = appearance68;
			ComboBoxCompanyTo.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
			ComboBoxCompanyTo.DisplayLayout.Override.CellPadding = 0;
			appearance69.BackColor = System.Drawing.SystemColors.Control;
			appearance69.BackColor2 = System.Drawing.SystemColors.ControlDark;
			appearance69.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
			appearance69.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
			appearance69.BorderColor = System.Drawing.SystemColors.Window;
			ComboBoxCompanyTo.DisplayLayout.Override.GroupByRowAppearance = appearance69;
			appearance70.TextHAlignAsString = "Left";
			ComboBoxCompanyTo.DisplayLayout.Override.HeaderAppearance = appearance70;
			ComboBoxCompanyTo.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
			ComboBoxCompanyTo.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
			appearance71.BackColor = System.Drawing.SystemColors.Window;
			appearance71.BorderColor = System.Drawing.Color.Silver;
			ComboBoxCompanyTo.DisplayLayout.Override.RowAppearance = appearance71;
			ComboBoxCompanyTo.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
			appearance72.BackColor = System.Drawing.SystemColors.ControlLight;
			ComboBoxCompanyTo.DisplayLayout.Override.TemplateAddRowAppearance = appearance72;
			ComboBoxCompanyTo.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
			ComboBoxCompanyTo.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
			ComboBoxCompanyTo.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
			ComboBoxCompanyTo.DropDownSearchMethod = Infragistics.Win.UltraWinGrid.DropDownSearchMethod.Linear;
			ComboBoxCompanyTo.Editable = true;
			ComboBoxCompanyTo.FilterString = "";
			ComboBoxCompanyTo.GenericListType = Micromind.Common.Data.GenericListTypes.FixedAssetCompany;
			ComboBoxCompanyTo.HasAllAccount = false;
			ComboBoxCompanyTo.HasCustom = false;
			ComboBoxCompanyTo.IsDataLoaded = false;
			ComboBoxCompanyTo.IsSingleColumn = false;
			ComboBoxCompanyTo.Location = new System.Drawing.Point(340, 240);
			ComboBoxCompanyTo.MaxDropDownItems = 12;
			ComboBoxCompanyTo.Name = "ComboBoxCompanyTo";
			ComboBoxCompanyTo.ShowInactiveItems = false;
			ComboBoxCompanyTo.ShowQuickAdd = true;
			ComboBoxCompanyTo.Size = new System.Drawing.Size(106, 20);
			ComboBoxCompanyTo.TabIndex = 30;
			ComboBoxCompanyTo.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
			comboBoxCountryFrom.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			comboBoxCountryFrom.CustomReportFieldName = "";
			comboBoxCountryFrom.CustomReportKey = "";
			comboBoxCountryFrom.CustomReportValueType = 1;
			comboBoxCountryFrom.DescriptionTextBox = null;
			appearance73.BackColor = System.Drawing.SystemColors.Window;
			appearance73.BorderColor = System.Drawing.SystemColors.InactiveCaption;
			comboBoxCountryFrom.DisplayLayout.Appearance = appearance73;
			comboBoxCountryFrom.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
			comboBoxCountryFrom.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
			appearance74.BackColor = System.Drawing.SystemColors.ActiveBorder;
			appearance74.BackColor2 = System.Drawing.SystemColors.ControlDark;
			appearance74.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
			appearance74.BorderColor = System.Drawing.SystemColors.Window;
			comboBoxCountryFrom.DisplayLayout.GroupByBox.Appearance = appearance74;
			appearance75.ForeColor = System.Drawing.SystemColors.GrayText;
			comboBoxCountryFrom.DisplayLayout.GroupByBox.BandLabelAppearance = appearance75;
			comboBoxCountryFrom.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
			appearance76.BackColor = System.Drawing.SystemColors.ControlLightLight;
			appearance76.BackColor2 = System.Drawing.SystemColors.Control;
			appearance76.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
			appearance76.ForeColor = System.Drawing.SystemColors.GrayText;
			comboBoxCountryFrom.DisplayLayout.GroupByBox.PromptAppearance = appearance76;
			comboBoxCountryFrom.DisplayLayout.MaxColScrollRegions = 1;
			comboBoxCountryFrom.DisplayLayout.MaxRowScrollRegions = 1;
			appearance77.BackColor = System.Drawing.SystemColors.Window;
			appearance77.ForeColor = System.Drawing.SystemColors.ControlText;
			comboBoxCountryFrom.DisplayLayout.Override.ActiveCellAppearance = appearance77;
			appearance78.BackColor = System.Drawing.SystemColors.Highlight;
			appearance78.ForeColor = System.Drawing.SystemColors.HighlightText;
			comboBoxCountryFrom.DisplayLayout.Override.ActiveRowAppearance = appearance78;
			comboBoxCountryFrom.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
			comboBoxCountryFrom.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
			appearance79.BackColor = System.Drawing.SystemColors.Window;
			comboBoxCountryFrom.DisplayLayout.Override.CardAreaAppearance = appearance79;
			appearance80.BorderColor = System.Drawing.Color.Silver;
			appearance80.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
			comboBoxCountryFrom.DisplayLayout.Override.CellAppearance = appearance80;
			comboBoxCountryFrom.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
			comboBoxCountryFrom.DisplayLayout.Override.CellPadding = 0;
			appearance81.BackColor = System.Drawing.SystemColors.Control;
			appearance81.BackColor2 = System.Drawing.SystemColors.ControlDark;
			appearance81.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
			appearance81.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
			appearance81.BorderColor = System.Drawing.SystemColors.Window;
			comboBoxCountryFrom.DisplayLayout.Override.GroupByRowAppearance = appearance81;
			appearance82.TextHAlignAsString = "Left";
			comboBoxCountryFrom.DisplayLayout.Override.HeaderAppearance = appearance82;
			comboBoxCountryFrom.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
			comboBoxCountryFrom.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
			appearance83.BackColor = System.Drawing.SystemColors.Window;
			appearance83.BorderColor = System.Drawing.Color.Silver;
			comboBoxCountryFrom.DisplayLayout.Override.RowAppearance = appearance83;
			comboBoxCountryFrom.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
			appearance84.BackColor = System.Drawing.SystemColors.ControlLight;
			comboBoxCountryFrom.DisplayLayout.Override.TemplateAddRowAppearance = appearance84;
			comboBoxCountryFrom.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
			comboBoxCountryFrom.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
			comboBoxCountryFrom.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
			comboBoxCountryFrom.DropDownSearchMethod = Infragistics.Win.UltraWinGrid.DropDownSearchMethod.Linear;
			comboBoxCountryFrom.Editable = true;
			comboBoxCountryFrom.FilterString = "";
			comboBoxCountryFrom.HasAllAccount = false;
			comboBoxCountryFrom.HasCustom = false;
			comboBoxCountryFrom.IsDataLoaded = false;
			comboBoxCountryFrom.Location = new System.Drawing.Point(203, 212);
			comboBoxCountryFrom.MaxDropDownItems = 12;
			comboBoxCountryFrom.MaxLength = 15;
			comboBoxCountryFrom.Name = "comboBoxCountryFrom";
			comboBoxCountryFrom.ShowInactiveItems = false;
			comboBoxCountryFrom.ShowQuickAdd = true;
			comboBoxCountryFrom.Size = new System.Drawing.Size(110, 20);
			comboBoxCountryFrom.TabIndex = 31;
			comboBoxCountryFrom.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
			comboBoxCountryTo.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			comboBoxCountryTo.CustomReportFieldName = "";
			comboBoxCountryTo.CustomReportKey = "";
			comboBoxCountryTo.CustomReportValueType = 1;
			comboBoxCountryTo.DescriptionTextBox = null;
			appearance85.BackColor = System.Drawing.SystemColors.Window;
			appearance85.BorderColor = System.Drawing.SystemColors.InactiveCaption;
			comboBoxCountryTo.DisplayLayout.Appearance = appearance85;
			comboBoxCountryTo.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
			comboBoxCountryTo.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
			appearance86.BackColor = System.Drawing.SystemColors.ActiveBorder;
			appearance86.BackColor2 = System.Drawing.SystemColors.ControlDark;
			appearance86.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
			appearance86.BorderColor = System.Drawing.SystemColors.Window;
			comboBoxCountryTo.DisplayLayout.GroupByBox.Appearance = appearance86;
			appearance87.ForeColor = System.Drawing.SystemColors.GrayText;
			comboBoxCountryTo.DisplayLayout.GroupByBox.BandLabelAppearance = appearance87;
			comboBoxCountryTo.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
			appearance88.BackColor = System.Drawing.SystemColors.ControlLightLight;
			appearance88.BackColor2 = System.Drawing.SystemColors.Control;
			appearance88.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
			appearance88.ForeColor = System.Drawing.SystemColors.GrayText;
			comboBoxCountryTo.DisplayLayout.GroupByBox.PromptAppearance = appearance88;
			comboBoxCountryTo.DisplayLayout.MaxColScrollRegions = 1;
			comboBoxCountryTo.DisplayLayout.MaxRowScrollRegions = 1;
			appearance89.BackColor = System.Drawing.SystemColors.Window;
			appearance89.ForeColor = System.Drawing.SystemColors.ControlText;
			comboBoxCountryTo.DisplayLayout.Override.ActiveCellAppearance = appearance89;
			appearance90.BackColor = System.Drawing.SystemColors.Highlight;
			appearance90.ForeColor = System.Drawing.SystemColors.HighlightText;
			comboBoxCountryTo.DisplayLayout.Override.ActiveRowAppearance = appearance90;
			comboBoxCountryTo.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
			comboBoxCountryTo.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
			appearance91.BackColor = System.Drawing.SystemColors.Window;
			comboBoxCountryTo.DisplayLayout.Override.CardAreaAppearance = appearance91;
			appearance92.BorderColor = System.Drawing.Color.Silver;
			appearance92.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
			comboBoxCountryTo.DisplayLayout.Override.CellAppearance = appearance92;
			comboBoxCountryTo.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
			comboBoxCountryTo.DisplayLayout.Override.CellPadding = 0;
			appearance93.BackColor = System.Drawing.SystemColors.Control;
			appearance93.BackColor2 = System.Drawing.SystemColors.ControlDark;
			appearance93.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
			appearance93.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
			appearance93.BorderColor = System.Drawing.SystemColors.Window;
			comboBoxCountryTo.DisplayLayout.Override.GroupByRowAppearance = appearance93;
			appearance94.TextHAlignAsString = "Left";
			comboBoxCountryTo.DisplayLayout.Override.HeaderAppearance = appearance94;
			comboBoxCountryTo.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
			comboBoxCountryTo.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
			appearance95.BackColor = System.Drawing.SystemColors.Window;
			appearance95.BorderColor = System.Drawing.Color.Silver;
			comboBoxCountryTo.DisplayLayout.Override.RowAppearance = appearance95;
			comboBoxCountryTo.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
			appearance96.BackColor = System.Drawing.SystemColors.ControlLight;
			comboBoxCountryTo.DisplayLayout.Override.TemplateAddRowAppearance = appearance96;
			comboBoxCountryTo.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
			comboBoxCountryTo.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
			comboBoxCountryTo.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
			comboBoxCountryTo.DropDownSearchMethod = Infragistics.Win.UltraWinGrid.DropDownSearchMethod.Linear;
			comboBoxCountryTo.Editable = true;
			comboBoxCountryTo.FilterString = "";
			comboBoxCountryTo.HasAllAccount = false;
			comboBoxCountryTo.HasCustom = false;
			comboBoxCountryTo.IsDataLoaded = false;
			comboBoxCountryTo.Location = new System.Drawing.Point(340, 214);
			comboBoxCountryTo.MaxDropDownItems = 12;
			comboBoxCountryTo.MaxLength = 15;
			comboBoxCountryTo.Name = "comboBoxCountryTo";
			comboBoxCountryTo.ShowInactiveItems = false;
			comboBoxCountryTo.ShowQuickAdd = true;
			comboBoxCountryTo.Size = new System.Drawing.Size(106, 20);
			comboBoxCountryTo.TabIndex = 32;
			comboBoxCountryTo.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
			base.AcceptButton = buttonOK;
			base.AutoScaleDimensions = new System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			BackColor = System.Drawing.Color.WhiteSmoke;
			base.CancelButton = buttonClose;
			base.ClientSize = new System.Drawing.Size(477, 314);
			base.Controls.Add(comboBoxCountryTo);
			base.Controls.Add(comboBoxCountryFrom);
			base.Controls.Add(ComboBoxCompanyTo);
			base.Controls.Add(ComboBoxCompanyFrom);
			base.Controls.Add(label8);
			base.Controls.Add(label5);
			base.Controls.Add(label4);
			base.Controls.Add(label3);
			base.Controls.Add(radioButtoncompany);
			base.Controls.Add(radioButtoncountry);
			base.Controls.Add(radioButtonDivision);
			base.Controls.Add(label1);
			base.Controls.Add(label7);
			base.Controls.Add(comboBoxFromDivision);
			base.Controls.Add(comboBoxToDepartment);
			base.Controls.Add(radioButtonDepartment);
			base.Controls.Add(comboBoxToDivision);
			base.Controls.Add(label2);
			base.Controls.Add(comboBoxFromDepartment);
			base.Controls.Add(buttonClose);
			base.Controls.Add(checkBoxShowInactive);
			base.Controls.Add(label6);
			base.Controls.Add(ultraGroupBox1);
			base.Controls.Add(buttonOK);
			base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
			base.Icon = (System.Drawing.Icon)resources.GetObject("$this.Icon");
			base.MaximizeBox = false;
			base.Name = "FixedAssetListReport";
			Text = "Fixed Asset List ";
			((System.ComponentModel.ISupportInitialize)ultraGroupBox1).EndInit();
			ultraGroupBox1.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)comboBoxFromDivision).EndInit();
			((System.ComponentModel.ISupportInitialize)comboBoxToDivision).EndInit();
			((System.ComponentModel.ISupportInitialize)comboBoxFromDepartment).EndInit();
			((System.ComponentModel.ISupportInitialize)comboBoxToDepartment).EndInit();
			((System.ComponentModel.ISupportInitialize)ComboBoxCompanyFrom).EndInit();
			((System.ComponentModel.ISupportInitialize)ComboBoxCompanyTo).EndInit();
			((System.ComponentModel.ISupportInitialize)comboBoxCountryFrom).EndInit();
			((System.ComponentModel.ISupportInitialize)comboBoxCountryTo).EndInit();
			ResumeLayout(false);
			PerformLayout();
		}
	}
}
