namespace Micromind.Common.Data
{
	public enum EntityTypesEnum
	{
		None = 0,
		Customers = 1,
		Vendors = 2,
		Partners = 3,
		Employees = 4,
		Leads = 5,
		Jobs = 6,
		Opportunities = 7,
		Competitors = 8,
		Activities = 9,
		BankFacilityGroups = 10,
		Vehicles = 11,
		Transactions = 12,
		Candidates = 13,
		Properties = 14,
		PropertyUnits = 0xF,
		CompanyDocuments = 0x10,
		EmpDependents = 17,
		TenancyContracts = 18,
		Acccounts = 19,
		Collaterals = 20,
		PassportControl = 21,
		Contacts = 22,
		ExternalReports = 23,
		Horse = 24,
		Items = 25,
		Lawyer = 26,
		CaseParty = 27,
		LegalActivitys = 28,
		CaseClients = 29,
		LegalActions = 28,
		EmpPositions = 30,
		JobExpenseIssue = 0x1F,
		JobMaterialEstimation = 0x20,
		JobClosing = 33,
		JobsBilling = 34,
		JobMaintenanceEntry = 35,
		Absconding = 36,
		Patients = 37,
		JobTask = 38
	}
}
